Fix CLI behaviour for some basic use-cases
Basic behaviours:

1. Running `korectl` without any arguments

    It prints the help.

    Exit code: 0 (default behaviour)

1. Running `korectl` with an unknown command, e.g. `korectl foo``

    ```
    Error: unknown command "foo"

    Please run `korectl help` to see all available commands.
    ```

    Exit code: 1

1. Any usage errors, e.g. `korectl --foo`

    ```
    Error: flag provided but not defined: -foo
    ```

    Exit code: 1

The `CommandNotFound` handler wasn't called as the default action was defined.
This means the first parameter was considered as an argument instead of a command name.